micronaut:
  application:
    name: datatest
datasources:
  testdatasource:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  testdatasource:
    entity-scan:
      packages: com.example
      enabled: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
